import type { Booking, InventoryItem } from "./types";

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: "inv-1",
    name: "Tenda Roder 5x10m",
    category: "Tenda & Struktur",
    location: "Gudang Cikarang",
    pricePerDay: 850_000,
    totalUnit: 8,
    unitMaintenance: 1,
  },
  {
    id: "inv-2",
    name: "Kursi Chiavari Putih",
    category: "Furnitur",
    location: "Gudang Pusat",
    pricePerDay: 15_000,
    totalUnit: 200,
    unitMaintenance: 0,
  },
  {
    id: "inv-3",
    name: 'Sound System JBL 15"',
    category: "Audio",
    location: "Gudang Pusat",
    pricePerDay: 450_000,
    totalUnit: 6,
    unitMaintenance: 0,
  },
  {
    id: "inv-4",
    name: "Genset Silent 20kVA",
    category: "Elektrikal",
    location: "Gudang Cikarang",
    pricePerDay: 1_200_000,
    totalUnit: 4,
    unitMaintenance: 1,
  },
  {
    id: "inv-5",
    name: "LED Screen P3 (per panel)",
    category: "Visual",
    location: "Gudang Pusat",
    pricePerDay: 350_000,
    totalUnit: 40,
    unitMaintenance: 2,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: "bk-1",
    itemId: "inv-1",
    namaKlien: "PT Sinergi Membangun",
    teleponKlien: "0812-3456-7890",
    tanggalMulai: "2026-09-10",
    tanggalSelesai: "2026-09-12",
    jumlahUnit: 3,
    status: "Dikonfirmasi",
    statusPembayaran: "DP",
  },
  {
    id: "bk-2",
    itemId: "inv-3",
    namaKlien: "Yayasan Bina Cita",
    teleponKlien: "0813-2345-6789",
    tanggalMulai: "2026-09-09",
    tanggalSelesai: "2026-09-09",
    jumlahUnit: 2,
    status: "Menunggu",
    statusPembayaran: "Belum Bayar",
  },
  {
    id: "bk-3",
    itemId: "inv-2",
    namaKlien: "Wedding Andra & Kirana",
    teleponKlien: "0821-9988-7766",
    tanggalMulai: "2026-09-15",
    tanggalSelesai: "2026-09-16",
    jumlahUnit: 150,
    status: "Dikonfirmasi",
    statusPembayaran: "Lunas",
  },
  {
    id: "bk-4",
    itemId: "inv-4",
    namaKlien: "Konser Amal Kota",
    teleponKlien: "0857-1122-3344",
    tanggalMulai: "2026-09-07",
    tanggalSelesai: "2026-09-08",
    jumlahUnit: 2,
    status: "Dikonfirmasi",
    statusPembayaran: "DP",
  },
];
