import type { BoothProject, MaterialItem } from "./types";

export const INITIAL_MATERIALS: MaterialItem[] = [
  {
    id: "mt-1",
    name: "Multiplek 18mm",
    category: "Kayu & Panel",
    unit: "lembar",
    location: "Gudang Cikarang",
    stock: 120,
    minStock: 30,
    pricePerUnit: 285_000,
  },
  {
    id: "mt-2",
    name: "Cat Duco Putih",
    category: "Cat & Finishing",
    unit: "liter",
    location: "Gudang Pusat",
    stock: 18,
    minStock: 20,
    pricePerUnit: 165_000,
  },
  {
    id: "mt-3",
    name: "Hollow Besi 4x4",
    category: "Hardware & Rangka",
    unit: "batang",
    location: "Gudang Cikarang",
    stock: 60,
    minStock: 15,
    pricePerUnit: 95_000,
  },
  {
    id: "mt-4",
    name: "Lampu LED Strip",
    category: "Elektrikal",
    unit: "meter",
    location: "Gudang Pusat",
    stock: 40,
    minStock: 25,
    pricePerUnit: 45_000,
  },
  {
    id: "mt-5",
    name: "Baut & Mur Set",
    category: "Hardware & Rangka",
    unit: "set",
    location: "Gudang Pusat",
    stock: 200,
    minStock: 50,
    pricePerUnit: 12_000,
  },
  {
    id: "mt-6",
    name: "Vinyl Sticker Print",
    category: "Cat & Finishing",
    unit: "meter",
    location: "Gudang Pusat",
    stock: 45,
    minStock: 10,
    pricePerUnit: 75_000,
  },
];

export const INITIAL_BOOTH_PROJECTS: BoothProject[] = [
  {
    id: "bp-1",
    name: "Booth Pameran IIMS 2026",
    namaKlien: "PT Auto Perkasa",
    lokasiAcara: "JIExpo Kemayoran",
    status: "Produksi",
    tanggalMulai: "2026-08-25",
    tanggalInstalasi: "2026-09-14",
    budget: 185_000_000,
    statusPembayaran: "DP",
    materials: [
      { materialId: "mt-1", qty: 40 },
      { materialId: "mt-3", qty: 20 },
      { materialId: "mt-2", qty: 10 },
    ],
  },
  {
    id: "bp-2",
    name: "Booth Retail Kopi Kenangan Lokal",
    namaKlien: "Kopi Kenangan Lokal",
    lokasiAcara: "Mall Kelapa Gading",
    status: "Desain",
    tanggalMulai: "2026-09-05",
    tanggalInstalasi: "2026-09-25",
    budget: 65_000_000,
    statusPembayaran: "Belum Bayar",
    materials: [
      { materialId: "mt-1", qty: 15 },
      { materialId: "mt-6", qty: 20 },
    ],
  },
  {
    id: "bp-3",
    name: "Booth Corporate Bank Mitra Sejahtera",
    namaKlien: "Bank Mitra Sejahtera",
    lokasiAcara: "Ballroom Ritz-Carlton Jakarta",
    status: "Finishing",
    tanggalMulai: "2026-08-15",
    tanggalInstalasi: "2026-09-10",
    budget: 220_000_000,
    statusPembayaran: "DP",
    materials: [
      { materialId: "mt-1", qty: 30 },
      { materialId: "mt-3", qty: 25 },
      { materialId: "mt-4", qty: 15 },
      { materialId: "mt-5", qty: 40 },
    ],
  },
  {
    id: "bp-4",
    name: "Booth Festival Kuliner Nusantara",
    namaKlien: "Yayasan Peduli Anak",
    lokasiAcara: "GBK Senayan",
    status: "Selesai",
    tanggalMulai: "2026-07-20",
    tanggalInstalasi: "2026-08-05",
    budget: 40_000_000,
    statusPembayaran: "Lunas",
    materials: [
      { materialId: "mt-1", qty: 10 },
      { materialId: "mt-2", qty: 5 },
    ],
  },
  {
    id: "bp-5",
    name: "Booth Konser Amal Kota",
    namaKlien: "Konser Amal Kota",
    lokasiAcara: "ICE BSD City",
    status: "Dibatalkan",
    tanggalMulai: "2026-09-01",
    tanggalInstalasi: "2026-09-20",
    budget: 30_000_000,
    statusPembayaran: "Belum Bayar",
    materials: [],
    catatan: "Dibatalkan klien karena perubahan anggaran acara.",
  },
];
